# render.yaml - For deploying backend to Render.com
services:
  - type: web
    name: myscheme-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    python:
      version: 3.9
    envVars:
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: JWT_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /api/health
    plan: free

databases:
  - name: myscheme-db
    databaseName: myscheme
    user: myscheme_user
    plan: free
    type: mongodb