services:
  - type: web
    name: myscheme-backend
    runtime: python
    pythonVersion: "3.9.16"
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python -m gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 app:app
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: myscheme-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: UPLOAD_FOLDER
        value: "/var/data/uploads"
    healthCheckPath: /api/health
    plan: free
    disk:
      name: uploads
      mountPath: /var/data/uploads
      sizeGB: 1

databases:
  - name: myscheme-db
    databaseName: myscheme
    user: myscheme_admin
    plan: free
    type: mongodb