services:
  - type: web
    name: govscheme-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        required: false  # Only if using AI features
      - key: PYTHON_VERSION
        value: 3.9.13
    healthCheckPath: /health